name = "SparseArraysBaseNext"
uuid = "d239194b-8157-4d49-a0f1-e790eb72a729"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BroadcastMapConversion = "4a4adec5-520f-4750-bb37-d5e66b4ddeb2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"

[sources]
BroadcastMapConversion = {url = "https://github.com/ITensor/BroadcastMapConversion.jl"}
TypeParameterAccessors = {url = "https://github.com/ITensor/TypeParameterAccessors.jl"}

[compat]
Adapt = "4.1.1"
Aqua = "0.8.9"
ArrayLayouts = "1.10.4"
BroadcastMapConversion = "0.1.0"
LinearAlgebra = "1.10"
Test = "1.10"
TypeParameterAccessors = "0.1.0"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
