[deps]
BroadcastMapConversion = "4a4adec5-520f-4750-bb37-d5e66b4ddeb2"
SparseArraysBaseNext = "d239194b-8157-4d49-a0f1-e790eb72a729"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"

[sources]
BroadcastMapConversion = {url = "https://github.com/ITensor/BroadcastMapConversion.jl"}
SparseArraysBaseNext = {path = ".."}
TypeParameterAccessors = {url = "https://github.com/ITensor/TypeParameterAccessors.jl"}
